### ISSUE TITLE
Priv app support? 

### ISSUE THREAD

**Issue by Quackdoc** [keymapperorg/KeyMapper#1027]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

would it be possible to install keymapper as a priv-app and get features like auto startup and not needing keyboard etc?

**Comment by sds100** [comment]
Hi, you can do this right now but even then it won't be able to since the permissions required to do that are only granted to packages which are signed with the same key as the operating system. This means that the app must be compiled with the operating system installed on your device, which isn't possible for us.
