### ISSUE TITLE
Feature request: swipe screen, scroll, or adb command

### ISSUE THREAD

**Issue by Efreak** [keymapperorg/KeyMapper#1082]
I'd like to make the down button scroll down in the browser about 3/4 of a screen, however the dpad down scrolls only a single line, and page up/down scrolls too far (the top of the screen begins where the bottom was cut off rather than overlapping a few lines, and adding pgdn+dpad up just scrolls to top).

This should probably be in my userscript, really, but I'm already at my limits with scripting requesting fullscreen by tapping on a title without access to devtools. Use case: I'm reading stories, comics, news, etc in the browser.

Either ability to set a swipe, ability to scroll (I'm not sure if accessibility provides scrolling features), or ability to directly enter a command to be sent to Shizuku (`input touchscreen`, etc). This last would probably be useful regardless, as it would allow other functions as well. 

Edit: I didn't look at previous issue, I see swiping is already requested. I'll leave this open, since it has other suggestions (scroll, adb command)

**Comment by noenic** [comment]
long press and swipe are the same thing, but I think they are not in the accessibility module, That's why it's quite difficult to add,
Running a command in shell would be awesome but for now there is a workaround with termux.

Actually there is a complete workaround for swiping as well. Simply configuration termux to allow external apps to access the environment, then send a service intent with Keymapper to termux and run a script.

On termux create the script you want to execute (note for input like touchscreen,keyevent,ect.. you can use adb shell inside termux) 

I have everything ready to go but on my android head unit the keys are not detected as triggers so that's kinda stoping de wheel

**Comment by sds100** [comment]
Hi @Efreak! I think your scrolling request is possible and there is already an issue for it #207 and the adb commands would be here #661
