### ISSUE TITLE
Hi, dear developers, can you support more in-vehicle devices

### ISSUE THREAD

**Issue by ulafox** [keymapperorg/KeyMapper#1295]
I am preparing to use this software for in-car Android devices, I found that some in-car devices can be monitored by this software to button feedback, but my car can't, I have found the reason and solution, I hope it can be supported in future versions!
As long as we can get the system logs, we can monitor the buttons of the on-board equipment!
We can take advantage of
android:sharedUserId="android.uid.system" can be used on any device to monitor the buttons of any Android device!
I ended up posting a picture of me trying to grant permission unsuccessfully

**Comment by ulafox** [comment]
![Uploading IMG_20240909_102239.jpg…]()

**Comment by ulafox** [comment]
![IMG_20240909_102239](https://github.com/user-attachments/assets/c6f5f44a-ca4e-4ef2-adc0-fd096ae4cc9b)

**Comment by ulafox** [comment]
At the moment, we can't detect the buttons of the car's steering wheel, and we need to add the system log attribute to do so

**Comment by Imold** [comment]
The reason you couldn't grant `android.permission.READ_LOGS` is because KeyMapper doesn't support it, it's not in [AndroidManifest.xml](https://github.com/keymapperorg/KeyMapper/blob/develop/app/src/main/AndroidManifest.xml). Also KeyMapper is in maintenance mode, so if you need something that can read logs, you may want to look for something else. Maybe something like Automate, MacroDroid, or Tasker would be better suited for what you're trying to do.

**Comment by sds100** [comment]
Closing this because simply adding READ_LOGS permission won't make the app detect buttons without extra work.
