### ISSUE TITLE
[Bug]: Accessibility service disables when stop service triggered 

### ISSUE THREAD

**Issue by HusniMuhammad** [keymapperorg/KeyMapper#1300]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [x] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
[Bug]: Accessibility service disables when app service stops

**To Reproduce**
Open the app, click stop service, again open the app

**Expected behavior**
Don't ask again and again
(Remembering accessibility permission)

**Screenshots**

**Smartphone (please complete the following information) **
 - Device: Realme C11
 - Android version:11 

**Additional context**

**Comment by sds100** [comment]
Hi, is this not intended behaviour? If you stop the service then it should turn off

**Comment by HusniMuhammad** [comment]
No other apps like termux, Nova launcher don't behave this way for accessibility permission

**Comment by sds100** [comment]
That is because they don't rely on the accessibility service for the entire app to work. You can still open Key Mapper even if the service is stopped

**Comment by HusniMuhammad** [comment]
Termux,Nova launcher are also don't rely on the accessibility service for the entire app to work

**Comment by sds100** [comment]
I don't understand what the issue is, can you create a screen recording?

**Comment by HusniMuhammad** [comment]
> I don't understand what the issue is, can you create a screen recording?


https://github.com/user-attachments/assets/e5687492-0fb9-4891-a4d0-ad165ad2b33e

**Comment by sds100** [comment]
Ah, I see. Thats because you created an action shortcut. Because in Key Mapper some actions require the accessibility service and some don't i just made it so that you can only execute actions if you have it turned on. I don't see why you need to turn the service off, it doesnt affect battery life or anything - even though some phones say they do.

**Comment by HusniMuhammad** [comment]
Short period of time it's don't affect battery standup time, running this app in for  **entire cycle of battery** for small sequence of actions & for low processing devices can kill process for **out of memory**

**Comment by HusniMuhammad** [comment]
Is it possible to solve this issue? for me it's really helpful

**Comment by kms2302** [comment]
I'd also find it helpful

**Comment by sds100** [comment]
Sorry but this isn't going to be implemented. I suggest using an app like Automate or Tasker to do this instead. Key Mapper is designed for key mapping and not home screen shortcuts which is why it assumes you always want the accessibility service running, to break that assumption means I need to redo quite a bit of code.
